<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7837c2d2-2ebe-4478-bed1-19b4d64455bf</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.13">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.13" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
  </ItemGroup>

  <ItemGroup>
    <!-- Member 3 modules (Candidate + Recruitment). Other members register their own modules here. -->
    <ProjectReference Include="..\Modules\Candidate\Candidate.Infrastructure\Candidate.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Recruitment\Recruitment.Infrastructure\Recruitment.Infrastructure.csproj" />
    <ProjectReference Include="..\Shared\TalentIQ.Shared.Kernel\TalentIQ.Shared.Kernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Identity\Identity.Infrastructure\Identity.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Interview\Interview.Infrastructure\Interview.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Notification\Notification.Application\Notification.Application.csproj" />
    <ProjectReference Include="..\Modules\Notification\Notification.Infrastructure\Notification.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\AI\AI.Infrastructure\AI.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Analytics\Analytics.Infrastructure\Analytics.Infrastructure.csproj" />
  </ItemGroup>

</Project>
