<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>

  <ItemGroup>

    <ProjectReference Include="..\Interview.Domain\Interview.Domain.csproj" />
	<ProjectReference Include="..\..\..\Shared\TalentIQ.Shared.Kernel\TalentIQ.Shared.Kernel.csproj" />
	<ProjectReference Include="..\..\Notification\Notification.Application\Notification.Application.csproj" />
    <ProjectReference Include="..\..\Candidate\Candidate.Application\Candidate.Application.csproj" />
	<ProjectReference Include="..\..\Recruitment\Recruitment.Domain\Recruitment.Domain.csproj" />
	<ProjectReference Include="..\..\Identity\Identity.Application\Identity.Application.csproj" /> 
  </ItemGroup>

</Project>
